### ISSUE TITLE
PSK Support For EMQTT - user_lookup_fun

### ISSUE THREAD

**Issue by codewiget95** [emqtt/emqttd#1132]
#### Environment

- OS: Ubuntu 14
- Erlang/OTP: Up to date
- EMQ: 2.2 - emq-rlx

#### Description

I am working on adding Pre-Shared Key support for EMQ. According to the Erlang docs, "It is possible to enable pre-shared keys, but it is not enabled by default"  Source: https://manpages.debian.org/unstable/erlang-manpages/ssl.7.en.html

According to the docs, a psk_identity can be used as an ssl argument :
"{psk_identity, string()}

    Specifies the server identity hint, which the server presents to the client."

However, unlike with standard public keys, it requires the use of a user_lookup_fun, which is defined only here: 
"For Pre-Shared Key (PSK) cipher suites, the lookup fun is called by the client and server to determine the shared secret. When called by the client, PSKIdentity is set to the hint presented by the server or to undefined. When called by the server, PSKIdentity is the identity presented by the client."

So far, I have modified the basic erlang client/server model as shown below 
-module(s).
    -export([start/0, client/1, accept/1]).

    start() ->
       ssl:start(),
       server(4000).

    server(Port) ->
        {ok, LSocket} = ssl:listen(Port, [{psk_identity, "psk_identity.txt"}, {reuseaddr, true}, {active, false}]),
        spawn(fun() -> accept(LSocket) end).
        
    accept(LSocket) ->
       {ok, Socket} = ssl:transport_accept(LSocket),
       ok = ssl:ssl_accept(Socket),
	Pid = spawn(fun() ->
            io:format("Connection accepted ~p~n", [Socket]),
            loop(Socket)
       end),
       ssl:controlling_process(Socket, Pid),
       accept(LSocket).

    loop(Socket) ->
       ssl:setopts(Socket, [{active, once}]),
       receive
       {ssl,Sock, Data} ->
            io:format("Got packet: ~p~n", [Data]),
            ssl:send(Sock, Data),
            loop(Socket);
       {ssl_closed, Sock} ->
            io:format("Closing socket: ~p~n", [Sock]);
       Error ->
            io:format("Error on socket: ~p~n", [Error])
       end.

    client(N) ->
        {ok, Socket} = ssl:connect("localhost", 4000,  []),
        io:format("Client opened socket: ~p~n",[Socket]),
        ok = ssl:send(Socket, N),
        Value = receive
                {ssl,{sslsocket,new_ssl,_}, Data} ->
                    io:format("Client received: ~p~n",[Data])
                after 2000 ->
                    0
                end,
        ssl:close(Socket),
        Value.

Unfortunately, I get an error that the handshake was not successful because the handshake was still looking for public key information for the handshake. 

If you have any more in depth knowledge about the issue, please shed some light, I greatly appreciate it.

**Comment by codewiget95** [comment]
@zhengyupan , Do you have any experience with the user_lookup_fun? It cannot be that difficult to enable PSK, it just seems that there are a few small pieces and specs missing.

Thanks.

**Comment by zhengyupan** [comment]
@codewiget95 , 
my thought is that to use PSK, the client should include at least one psk-ciphersuite in its hello message to the server, otherwise the server will always check if there is any certificate available.  
In the RFC: 
> The client indicates its willingness to use pre-shared key
   authentication by including one or more PSK ciphersuites in the
   ClientHello message.  If the TLS server also wants to use pre-shared
   keys, it selects one of the PSK ciphersuites, ......

So I changed your code of client(N) a little:
`{ok, Socket} = ssl:connect("localhost", 4000, [{ciphers,[{psk, aes_256_cbc,sha512}]},{psk_identity, "abcde"}]),
`
Now the server is not looking for a cert any more, but it doesn't understand the SSLoption...
I did a  `rp(ssl:cipher_suites()).`  in shell, and find I don't have any PSK ciphersuite enabled... googled a lot trying to enable it, didn't get a clue.
Still working on it, If you have any progress on it, please kindly share.

**Comment by codewiget95** [comment]
@zhengyupan I run the same commands and get the same results. There don't seem to be and psk suites enabled. Yesterday, I posted to the Rabbit MQ support group on google and was pointed here in regards to user_lookup functions: https://github.com/erlang/otp/blob/32a1dca92c0f949ef6ce2c751b23aff82f9d998f/lib/ssl/test/ssl_test_lib.erl#L404

I'll comment again when I make more progress

**Comment by codewiget95** [comment]
@zhengyupan , running rp(ssl:cipher_suites(all)). yields all of the ciphers, one of which is the {psk, aes_256_cbc, sha} cipher that we need(sha replaced by sha512 is the only difference). Now, with the code modified and the correct cipher suite, I run it and now get an error with the psk_identity, so we can move past the cipher

**Comment by zhengyupan** [comment]
@codewiget95 it seem the PSK problem is solved, grats~ :)  I am closing this issue in this regard.
We can talk about how to build a plugin somewhere else. I am new to Erlang, I am sure my colleagues can do better by this topic than I can.

Btw, Which version of OTP you are on? I am on ubuntu 16.04 with Erlang/OTP 19 and OSX with Erlang/OTP 18. On this two version I tried your trick and got multiple psk suites, one iof them is {psk,aes_256_cbc,sha384}. If there is SHA version equal to or higher than the SHA256 available, I would suggest you using it, for that the original SHA (SHA-1) is considered as insecure nowadays.

**Comment by rauger** [comment]
@zhengyupan,

Looks like me and you are in the same boat! I just started learning Erlang too. I am using Erlang 19.2 on Ubuntu 14, but for that matter I'm no security expert yet so thank you for the tip on sha. 

Where would you like to talk about the plugin? If you have any resources that can explain them a bit better, please let me know! I would like to integrate this into the emq platform so that all of my connections can be using pre-shared keys.

And thank you very much for your help!

**Comment by codewiget95** [comment]
@zhengyupan,

I have read through the docs on EMQ extensively and through this "walkthrough" here: https://www.sakib.ninja/how-to-emq-plugin-development/ and I am missing a few core concepts.

To handle authentication hooks, it looks like I want to intercept authentication on session created or client connected, but the problem with those is that there are no arguments for the client options to check. For example, if I want to write code on top of a hook, how can I do that without knowing the client ssl opts?

Also, In the config file, I can specify a psk_secret that the client can use and the server will validate, but how do I then reference that from my erlang code? I know that cuttlefish does work on it, but how do I then reference it?

Thank you for your help!
