### ISSUE TITLE
Disable everything but SSL

### ISSUE THREAD

**Issue by rauger** [emqtt/emqttd#1155]
#### Environment

- OS: Ubuntu 14
- Erlang/OTP: 19
- EMQ: 2.2

#### Description

I need to disable web socket access, tcp, wss, and api. The only thing I want to allow access through is ssl. Is there any way to do that in the configuration, or is the only way to modify the source in emqttd_app and prevent the listeners from being started?

For that matter, is there an easy way to disable all of the built in authentication plugins without breaking everything? I would just like to use the mysql authentication and dont need the rest, when I delete them from the makefile and relx.config i get errors so there should be an easier way i think.

Thank you,

**Comment by emqplus** [comment]
@rauger

1.  Remove or comment the 'listener' configuration items in etc/emq.conf to disable a listener.
2. Just enable the emq_auth_mysql plugin.

**Comment by CallMeKanG** [comment]
@emqplus 
#### Environment

- OS: Windows Server 2016
- Erlang/OTP: I install the latest version(10.1.2020)
- EMQ: 3.4.5

#### Description

Hi, my scenario is different, I just want SSL connection, is there had any better way to disable web socket access, tcp, wss, and api, instead of remove or comment the 'listener' configuration items in etc/emq.conf to disable a listener.

Thank you
