### ISSUE TITLE
[error] ** System running to use fully qualified hostnames **

### ISSUE THREAD

**Issue by cjy37** [emqtt/emqttd#1348]
#### Environment

- OS: https://github.com/emqtt/emq-docker
- Erlang/OTP: https://github.com/emqtt/emq-docker
- EMQ: https://github.com/emqtt/emq-docker

#### Description
使用阿里云的容器服务，
1. Docker=A的服务编排中设置hostname=emqtt
2. Docker=B的服务编排中设置environment: EMQ_JOIN_CLUSTER=emqtt@emqtt

先启动A，等A正常了，再启动B，结果看到B的Log：
```
emqtt_emqtt-lb_1 | 2017-11-22T08:53:33.995182237Z ['2017-11-22T08:53:33Z']:waiting emqttd
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.027610741Z emqttd 2.3.0 is running now
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.447038052Z ['2017-11-22T08:53:34Z']:emqttd start
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.447764103Z ['2017-11-22T08:53:34Z']:emqttd try join emqtt@emqtt
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.965973408Z 08:53:34.962 [error] ** System running to use fully qualified hostnames **
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.965998136Z ** Hostname emqtt is illegal **
emqtt_emqtt-lb_1 | 2017-11-22T08:53:34.966787396Z Failed to join the cluster: {node_down,emqtt@emqtt}
```

补充，在B中，是可以ping到hostname=emqtt 的ip的，B用ip是可以Join到A的，environment: EMQ_JOIN_CLUSTER=emqtt@ip

**Comment by cjy37** [comment]
This issue is very important! Docker container ip maybe change on restart.

**Comment by adacaccia** [comment]
Hello,
apparently I've just hit this error on a just installed v4.2.1 image on K8s:

`(emqx@emqx-0.emqx.rtm.svc.cluster.local)1> 2020-07-28 13:55:14.480 [error] ** System running to use fully qualified hostnames **
** Hostname emqx-0 is illegal **
`
and you can see it correctly called himself "emqx@FQDN", so why is it staring at the hostname... everyone knows the hostname is shorter than the FQDN, anyway...

Here's the environment I'm passing to the v4.2.1. docker image:

`EMQX_CLUSTER__AUTOCLEAN=5m	 	
EMQX_CLUSTER__AUTOHEAL=on	 	
EMQX_CLUSTER__DISCOVERY=k8s	 	
EMQX_CLUSTER__K8S__ADDRESS_TYPE=hostname	 	
EMQX_CLUSTER__K8S__APISERVER=https://10.43.0.1:443	 	
EMQX_CLUSTER__K8S__APP_NAME=emqx	 	
EMQX_CLUSTER__K8S__NAMESPACE=rtm	 	
EMQX_CLUSTER__K8S__SERVICE_NAME=emqx	 	
EMQX_CLUSTER__NAME=rtmcl	 	
EMQX_NAME=emqx	 	
EMQX_NODE__COOKIE=cookie	 	
`
Please advise, as I'm really puzzled by this, since just yesterday I've successfully installed another emqx v4.2.1 cluster in a different namespace, and it's working very well!

**Comment by spring2maz** [comment]
@adacaccia could you try to add DEBUG=true to your environment variables and paste the output here ?
You may also try to set `EMQX_HOST` to the FQDN

**Comment by spring2maz** [comment]
did not notice that the issue has been resolved.
nonetheless, debug output could help us to understand what went wrong.
