### ISSUE TITLE
Fastlane subscription

### ISSUE THREAD

**Issue by bharat-mehta** [emqtt/emqttd#1594]
#### Environment

- OS: Ubuntu
- Erlang/OTP: 
- EMQ: 2.4.2

#### Description

I am new to EMQ.Can anyone explain how Fastlane subscription works in Emqx with an example. I have thousands of micro controllers sending signals and I am trying to understand , how can I benefit from fastlane subscription.

Many thanks.

**Comment by terry-xiaoyu** [comment]
@bharat-mehta hi, the message delivery in Fastlane subscriptions *should* be much more efficient than the normal ones, although I have not got the benchmarks comparing of the two. 

This is because, in contrast to the normal subscriptions, if a target client has subscribed to a "$fastlane" prefixed topic, the source client process would deliver the message to the target client process directly without having to go through the session process. 

Where the "process" talked about is "erlang process". The client processes are to handle the TCP sockets of the clients, while the session process is for maintaining the message queues and subscription states. The erlang message passing would be a significant overhead under a high load.

But it thus loses all features the 'session process' provides, i.e. message queues, QoS1 and QoS2 related procedures. So it is mainly used for QoS1.

**Comment by bharat-mehta** [comment]
@terry-xiaoyu  Thanks

**Comment by bharat-mehta** [comment]
@terry-xiaoyu Also is $fastlane good for backend subscription with wildcards ?

**Comment by terry-xiaoyu** [comment]
No other limitations. 

And yes, good for backend subscription, but use plugins with hook callbacks is a more efficient way.
