### ISSUE TITLE
I got messages different other broker (mosquitto, hivemq) 

### ISSUE THREAD

**Issue by krittanon-w** [emqtt/emqttd#1614]
#### Testing Environment
docker-image: emqtt version: 2.3.8 with default configuration
mqtt-client: mqtt.js and mosquitto

#### Description
*I tested publishing mqtt to a subscriber by Emq but I got difference result*
*Mosquitto and Hivemq broker is same but Emq difference*

##### connec
- clean_session=false
##### publish
- qos=1
- retain=true
##### subscribe
- qos=1

#### Testing timeline 
<img width="1083" alt="screen shot 2018-05-27 at 10 46 20 pm" src="https://user-images.githubusercontent.com/18285224/40588024-8e3fda5a-6201-11e8-9e63-603e7406d06e.png">

**Comment by terry-xiaoyu** [comment]
There might be a behavior difference when handling the `"duplicated subscription"` between these brokers.

In EMQ, if a client tries to subscribe a topic to which it has already subscribed, the subscription request will be discarded, as it is treated as 'duplicated subscription'. In this case a warning level log will be printed: 
`[warning] Session(client1): Duplicated subscribe: test/777, qos = 1`

And because you have set the `clean session flag`, the subscriptions of client1 (the 'test/777') have been stored in the broker. All the subsequent subscribes to 'test/777' will be regarded as 'duplicated', including the ones it sends after the connection has been established.

**Comment by krittanon-w** [comment]
Thanks for the prompt reply
1. How should I have to do to get the same result (Mosquitto, Hivemq)
2. I think this difference should solve because most people set **clean_session = false** to get old messages that clients can't receive and **retian=true** to get the last message. so that, when developer set those flag It should express the ability of each flag. But now, EMQ can choose just one feature (clean_sessen or retain).
3. from 2. if there are some project wanna move to use your broker (EMQ), the code that they have should be compatible with every broker and your broker (EMQ)

**Comment by DavidLiuXh** [comment]
Pay attention to this problem.

**Comment by terry-xiaoyu** [comment]
@DavidLiuXh @krittanon-w Hi, we're planing to fix this issue in 2.3.10.

**Comment by Gilbert-Wong** [comment]
This bug has been fixed in 2.3.11.

**Comment by krittanon-w** [comment]
Hi, @Gilbert-Wong you said "This bug has been fixed in 2.3.11" but I see only 2.3.10 in release tab and for that release 2.3.10 It has no release note that reference or tag to any issue. is there something incorrect?

**Comment by Gilbert-Wong** [comment]
Sorry for my ambiguous state. The bug has been fixed bug  in develop branch but did not merge into release tab 2.3.10,  so  we would merge it into next version v2.3.11
