### ISSUE TITLE
[error] failed to start connection on 0.0.0.0:1883 - enotconn

### ISSUE THREAD

**Issue by hbyscpp** [emqtt/emqttd#294]
in aliyun env,
lots of [error] failed to start connection on 0.0.0.0:1883 - enotconn
but emqttd can work

in config,can set ip bind

**Comment by erylee** [comment]
@hbyscpp, Please check issue: https://github.com/emqtt/esockd/issues/10

This issue is caused by aliyun's health check that will shutdown the TCP connection right after 3 way handshake. esockd 2.7.x close the socket quietly when 'enotconn' error happened.

If you build emqttd from source, please 'rebar update-deps' to update esockd.

**Comment by linbo** [comment]
Hi，

Any resource I can refer to?

How to find the reason is that aliyun health check close normal TCP connection，any flow I can reproduce it?

Thanks，
Linbo
