### ISSUE TITLE
Persist messages across broker reboots

### ISSUE THREAD

**Issue by ghost** [emqtt/emqttd#327]
@erylee are you planing to support persisting messages to LevelDB or some other datastore in the foreseable future? As of now, rebooting the broker causes all undelivered (and retained) messages to be lost, and it would be great if they were persistent.

**Comment by erylee** [comment]
@bmcustodio, There is a plan to persist MQTT messages. I am considering LevelDB, Cassandra, Kafka or a storage wrote from scratch. What's your suggestion?

**Comment by bmcustodio** [comment]
@erylee I'd put my money on Cassandra. That would be great as you get a lot of benefits you don't get with LevelDB or a custom storage.

**Comment by erylee** [comment]
Haha:) I really like Cassandra too. But that means users of emqttd need extra work to deploy and configure Cassandra. If we use LevelDB, we could integrate with eLevelDB library. Your idea?

**Comment by bmcustodio** [comment]
@erylee I would still go for Cassandra. Or, better yet and if you have the time, implement "agnostic" persistence and an adapter/plugin for Cassandra and another one for Level.

**Comment by erylee** [comment]
@bmcustodio, plan to support Cassandra and Kafka fist:)

**Comment by kennethalong** [comment]
I need this functionality as well.  I haven't used Cassandra, but Kafka is a real beast and has been very stable for us.  I like the plan!  Any ETA?

**Comment by erylee** [comment]
@kennethalong, I will integrate the broker with Kafka and Cassandra after 0.14.x released:)

**Comment by kennethalong** [comment]
This is great news!  Thanks for all your hard work.

**Comment by hsncr** [comment]
@erylee Any progress about this feature? Are you going to implement it any time soon?

**Comment by bangarharshit** [comment]
@erylee , Do you think something with really high throughput and low latency will be awesome. http://kkovacs.eu/cassandra-vs-mongodb-vs-couchdb-vs-redis . Tested Cassandra, and Couchbase. Need to test AeroSpike - http://stackoverflow.com/questions/25208914/has-anyone-worked-with-aerospike-how-does-it-compare-to-mongodb/25716540#25716540 . While they are awesome, they still add 30-50ms to queries. Aerospike really looks much better than Cassandra for storing messages and topics (taking it with pinch of salt since I still need to test it manually). It uses SSD and RAM. If the claims 95% of query less than 1ms then it will be really awesome (both fast and distributed). Also there is a UDF to create queue if needed.

**Comment by erylee** [comment]
@bangarharshit, I will check the docs:)

**Comment by aksswami** [comment]
@erylee Any updates on this?

**Comment by erylee** [comment]
@aksswami, sorry for late reply, preparing for 1.0 release these days. We will integrate emqttd with various backends including SQL or NoSQL databases when 1.0 is ready.

**Comment by mpoornima** [comment]
Now that 1.0 is out (congratulations BTW :)), any expected ETA for integration with a data store?

**Comment by bangarharshit** [comment]
@emqplus , how are you designing the message store? Is it through plugin and hooks again to store across different types of data store. I have implemented one for sql by replacing queue with mysql data-store. Loading it in the result list once the session starts and deleting it from sql once the packet id is acked. If you are working on it then I will probably skip it, otherwise I can generalize and contribute. I have three apis - fetch_message (which loads all the message when client comes online), add_message(which adds the message when the client is offline) and ack_message(which removes the message from data-store).

**Comment by mkj-git** [comment]
Any update about cassandra and Kafka integration ?

**Comment by emqplus** [comment]
Released a 'EMQPlus' Product to help persist MQTT messages.

**Comment by tristan-koen** [comment]
Where can we find this EMQPlus product?

**Comment by semir-karic** [comment]
Where can we find this EMQPlus product for persisting messages ?

**Comment by kerber** [comment]
I'm also looking for message persistence. I've done some searching, but I cannot find the mentioned EMQPlus project anywhere. Can you please direct us to it?

**Comment by opyate** [comment]
@kerber http://emqtt.com/products

**Comment by felipejfc** [comment]
at tfgco our solution is:

we created a bot [mqttbot](https://github.com/topfreegames/mqttbot) that subscribe to configurable topics and listen to all messages, it then persist every message into a elasticsearch that can be later searched to grab messages back, the very same mqttbot support plugins, it would be simple to create one to grab the  messages back...
