### ISSUE TITLE
The best way for persisting messages

### ISSUE THREAD

**Issue by rock59** [emqtt/emqttd#337]
I am not an erlanger.. I need to persist messages for future analysis.
Which is the best way for persisting messages in high loaded environment when publish performance is critical?

Persisitng directly in database(Riak or Cassandra) by an emqttd module 
or
Publish messages to Kafka and then consume messages and persist them by a Kfka consumer

**Comment by erylee** [comment]
@rock59, plan to support Kafka and Cassandra.

**Comment by danlg** [comment]
@emqplus is there any persistence possible with emqttd 1.1.3. On which database ?

**Comment by mikybone** [comment]
Hi
@emqplus thanks for hard work.
i have suggestion on database that used for pesistance messages:

**Couchbase** is best nosql database, **6x** faster than mongodb and others, please see http://www.couchbase.com/ that have many comparison papers.

**Comment by drasko** [comment]
[Scylla](http://www.scylladb.com/) is an interesting candidate: http://www.scylladb.com/technology/cassandra-vs-scylla-benchmark/

**Comment by drasko** [comment]
@emqplus in relation to: https://groups.google.com/forum/#!topic/rabbitmq-users/KVMNkAsW-ac, I think it is of crucial importance for scaling. We need either Kafka or Cassandra pipes out of each node, so that we can persist messages in a DB without subscription to `#` topic (but take data directly from within the node via plugin).

There is already community support for Kafka (https://github.com/vowstar/emqttd_plugin_kafka_bridge), so I think Cassandra plugin would be of higher urgency now.

Kafka is not easy to set-up (because Zookeeper) and if all that is needed is data storage into database (form all nodes in parallel) then I think Cassandra plugin will do.

**Comment by rock59** [comment]
@mikybone Couchbase is fast and easy to setup and cluster. Unfortunately Couchbase doesn't provide official SDK for Erlang. Commiunity drivers are old and almost obsolete.

http://stackoverflow.com/questions/10750986/couchbase-1-8-and-2-0-erlang-sdks-why-is-erlang-left-out

**Comment by emqplus** [comment]
We have released a 'EMQPlus' product to help persist MQTT messages in Redis, MySQL, PostgreSQL, MongoDB and Kafka. I'd like to close this issue now.

**Comment by edmandiesamonte** [comment]
Hi @emqplus, where can I find 'EMQPlus'? It seems that it is not documented or I'm just missing something. Thanks.
