### ISSUE TITLE
How do I know that the clients connect to the server and look the client sends the messages

### ISSUE THREAD

**Issue by huyp** [emqtt/emqttd#380]

**Comment by Prots** [comment]
You can write your own plugin, where you can dispatch any event provided by clients using enabled hooks.
Please see this code: https://github.com/emqtt/emqttd_plugin_template

**Comment by erylee** [comment]
@huyp, MQTT is a PubSub protocol and route messages by Topics. If you want to send messages, just publish to topic, it's not necessary to know if the clients are online, I think.

**Comment by abhidtu** [comment]
@huyp  have a look at this emqttd plugin written by me: 
https://github.com/abhidtu/emqttd_publish_client_activity

This plugin publishes a new message on all events when a client connect/disconnect/messageAck/sub/unsub 
I'm also working on integrating this plugin with kafka also so that it publishes messages on these events to kafka also.

Read readme.md for more details
