### ISSUE TITLE
Not able to start emqttd 

### ISSUE THREAD

**Issue by borntorock** [emqtt/emqttd#490]
I'm facing issue while starting emqttd after building using make && make dist.
Error:
emqttd failed to start within 15 seconds,
see the output of 'emqttd console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

Can anyone suggest how to work out for this issue and how to set the environment variable, WAIT_FOR_ERLANG.

**Comment by borntorock** [comment]
@erylee Can you Please help with this.

**Comment by erylee** [comment]
Hi @borntorock, sorry for late reply. Please start the broker in console mode first: 
```
./bin/emqttd console
```

**Comment by borntorock** [comment]
@erylee Thanks for your response! You mean I should first start the broker in console mode and then start emqttd. So, when I start the broker in console mode, it displays some stdout. Please suggest!

Please note whenever I recompiles EMQTTD using make && make dist again, I can start the broker in first go by executing the command: 
./bin/emqttd start

**Comment by borntorock** [comment]
@erylee Please let me know your suggestions to resolve this.

**Comment by vpotapev** [comment]
@borntorock I've the same symptoms, but in my case the problem was in wrong path which is calculated in the [emqttd](https://github.com/emqtt/emqttd/blob/1.1.2/rel/files/emqttd) script.
I've prepared .deb package contained emqttd, so the system was installed to **/opt/emqttd/** dir. When I tried to start emqttd using `/opt/emqttd/bin/emqttd start`, the pathname of the **$RUNNER_SCRIPT_DIR/$SCRIPT** ([line 150](https://github.com/emqtt/emqttd/blob/1.1.2/rel/files/emqttd#L150) of the emqttd bash script) was **/opt/emqttd//emqttd**, but it should be **/opt/emqttd/bin/emqttd**. I've changed the string to **$RUNNER_SCRIPT_DIR/bin/$SCRIPT**, and the problem was solved.
