### ISSUE TITLE
Kafka plugin roadmap

### ISSUE THREAD

**Issue by zishanbilal** [emqtt/emqttd#604]
Here is an urgent need of Kakfa connector to build IoT application.

**Comment by vowstar** [comment]
You can try this [emqttd_plugin_kafka_bridge] (https://github.com/vowstar/emqttd_plugin_kafka_bridge) plugin, which can publish messages from emqttd to kafka topic

https://github.com/vowstar/emqttd_plugin_kafka_bridge

**Comment by mkj-git** [comment]
So to use that plugin i will have to build emqttd from source right? Is it possible to provide it as other emqttd plug & play type plugin rather than building it explicitly

**Comment by vowstar** [comment]
@mkj-git It's just same as other plugin's usage. Provide compiled version is OK but you need match your mqttd version. And, this plugin is plug & play as other plugin does.

**Comment by MadDataScience** [comment]
@vowstar, I'm a little confused at how to add this. I'm trying it with https://github.com/emqtt/emq-relx/. I'm not sure where I should be running 
```
git submodule add -f https://github.com/msdevanms/emqttd_plugin_kafka_bridge.git plugins/emqttd_plugin_kafka_bridge
```
(Couple notes there: you need to update the README because the repo is now at `msdevanms` not `vowstar`. Also, I don't know if the fact that I had to use `-f` is an indication that I was in the wrong place, or if that is required when using `emq-relx`.)
I tried doing it in both `_rel/emqttd/` and in `_rel/emqttd/etc/` (which is where I found the `plugins` folder) but when I tried 
```
./bin/emqttd_ctl plugins load emqttd_plugin_kafka_bridge
```
in either case it said 
> load plugin error: not_found

Do you know what I'm doing wrong?
Thank you.
