### ISSUE TITLE
EMQ dops messages on subscribed topics after restart

### ISSUE THREAD

**Issue by frank-montyne** [emqtt/emqttd#931]
#### Environment

- OS: Linux
- Erlang/OTP: 19 [erts-8.2] [source-fbd2db2] [64-bit]
- EMQ: 2.0.7

#### Description
I have a durable client (clean session = false) that is subscribed to a topic (QoS 1). When the EMQ broker is restarted then messages for that topic are being dropped instead of being kept until the client reconnects. I even have to re-subscribe before I start receiving messages again. As far as I understand the broker should keep these messages until they can be delivered to the client. 

EMQ settings :
- mqtt.session.max_inflight = 0
- mqtt.queue.max_length = infinity
- mqtt.session.expired_after = 1w

Client used is Eclipse Paho with the following settings:
- clientId is the same on reconnect
- cleanSession = false
- QoS is the same on reconnect
- inflight messages set to very high number

Any ideas?
Thanks,
Frank Montyne

**Comment by frank-montyne** [comment]
I forget to mention that I'm using an SSL connection to the broker

Best regards,
Frank Montyne

**Comment by phanimahesh** [comment]
When the broker is restarted a lot of state is lost. If your interpretation of spec is correct (I'll have to check that, not sure), then subscriptions should be stored in mnesia and loaded on start.

My understanding of clean_sess = false is as follows: If there is a session existing on the server for this client id, attach to that instead of cleaning it and creating a new session. A clean_sess=false should not be considered a guarantee that the server will hold session state. It is the choice of the server(broker) whether the session will stick around when client is not connected, for how long, and whether it persists after reboot.

Out of curiosity, are there any other MQTT brokers that persist sessions across broker restarts?

**Comment by frank-montyne** [comment]
Look for example at HiveMQ. They state this explicitly in the documentation:

**File persistence**
By default, all persistence stores are backed by the file system of the machine HiveMQ is running on. So even if HiveMQ stops or restarts no state is lost and after restarting the broker, all clients keep their persistent sessions, all queued messages for offline persistent clients are preserved, MQTT message flows can resume and retained messages are available.

http://www.hivemq.com/docs/hivemq/latest/#mqtt-configuration-persistence-chapter

**Comment by phanimahesh** [comment]
emqttd stores its state in mnesia and uses `ram_copies` for all tables except `schema`, which means the state is lost on reboot. A quick fix is to use mnesia for everything and use `disc_copies`. But it will have a performance impact.

Another option is to store messages only for disconnected clients on disc, either in mnesia or some other fast datastore. vernemq seems to be using leveldb for a similar purpose.

@emqplus Thoughts?

**Comment by frank-montyne** [comment]
I would go for option 2 similar to VerneMQ. Performance is key when having a lot of traffic.

**Comment by opyate** [comment]
> I would go for option 2 similar to VerneMQ.

Another concern: [corruption detection](https://en.wikipedia.org/wiki/LevelDB#Bugs_and_reliability).

**Comment by frank-montyne** [comment]
Is there any progress on this issue? I tried v2.2 but the behavior is still the same

**Comment by syberkitten** [comment]
Hi

We're having the same issue here,
restart looses all retained subscriptions.

Since we rely on cleanSession=false
when client re-connects to a restarted broker.

It thinks that it is subscribed as clean=false
and thinks it will get retained messages but it does not!

Is there any work around we can use?
for example give the client a flag or something
saying that it has to re-subscribe to all topics ?

Thanks

**Comment by emqplus** [comment]
@syberkitten EMQ stores the offline messages in various backends, such as MySQL, MongoDB, PostgreSQL or Cassandra. We implement these features in an enterprise edition for there are too many supports for our customers.

Documentation on backends and bridges: http://emqx-enterprise-docs-en.readthedocs.io/en/latest/backends.html

**Comment by syberkitten** [comment]
Thanks @emqplus 
I did not know there is an enterprise version for EMQ, can you share
more details about ?

**Comment by emqplus** [comment]
@syberkitten Please contact `zhengyu.pan@emqtt.io` for more details about the product, who is our global support based in Germany.
