### ISSUE TITLE
Node running on console but can't start

### ISSUE THREAD

**Issue by Moolica23** [emqtt/emqttd#946]
I'm running emqttd on docker container
when I run the broker via ./emqttd console the result is : 
Erlang MQTT Broker 1.1.2 is running now

but when i try to start the node it gives me the 15 seconds error

**Comment by vowstar** [comment]
Please go to here to create a new issue:

https://github.com/emqtt/emq-docker/issues/new

Please add more information about:

Make sure you read and understand http://emqtt.io/docs/v2/index.html.
Use one of the two templates below and delete the rest.

- [ ] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Expected behavior

### Actual behavior

### Test code

Provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) which will reproduce the problem.

```bash
# add code here
```

### EMQ version
Which branch are you on? If you know the Git revision then add it here as well.

### Docker version

Which docker-engine version?

```bash
docker -v
```

How docker info?

```bash
docker info
```

### System

What system do you use?

### Hardware

How is the host machine?


-------------------------------------------------------------------------------
> FEATURE REQUEST

### Missing feature

### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?
